-- Generated by scripts/initial-ratings.ts — do not edit by hand.
-- Starting ratings derived from the group's 1–10 ratings and pre-app win history.

insert into public.players (name, initial_singles, initial_doubles, is_active)
values
  ('Tarang', 1678, 1678, true),
  ('Dhruv', 1643, 1643, true),
  ('Gaurav', 1600, 1600, true),
  ('Satyam', 1556, 1556, true),
  ('Manoj', 1546, 1546, true),
  ('Sunny', 1463, 1463, true),
  ('Shlok', 1427, 1427, true),
  ('Yatharth', 1407, 1407, true),
  ('Samrat', 1342, 1342, true),
  ('Manmeet', 1336, 1336, true),
  ('Monty', 1426, 1426, false),
  ('Gunjan', 1407, 1407, false),
  ('Nishant', 1403, 1403, false),
  ('Ashish', 1399, 1399, false),
  ('Swastik', 1398, 1398, false),
  ('Ronnie', 1380, 1380, false),
  ('Vinay', 1347, 1347, false),
  ('Praveer', 1305, 1305, false),
  ('Abhinav', 1287, 1287, false),
  ('Bhanu', 1287, 1287, false)
on conflict (name) do update
  set initial_singles = excluded.initial_singles,
      initial_doubles = excluded.initial_doubles,
      is_active = excluded.is_active;
