/**
 * Derive starting Elo ratings from the group's pre-app data.
 *
 * The legacy history only records the winning pair of each game (no losers,
 * no scores), so it can't be replayed as ordinary Elo matches. Instead:
 *
 *  1. Prior: map the group's 1–10 rating linearly onto Elo, 100 points per
 *     rating point, centred so the average active player sits at 1500.
 *     Players without a group rating start at the average of all rated players.
 *  2. Evidence: replay each recorded win as a win over an average (1500) team,
 *     with a deliberately small K so the history nudges rather than overrides.
 *  3. Re-centre the players who appear in the history so their average is
 *     unchanged; everyone else keeps their prior.
 *
 * Usage: npx tsx scripts/initial-ratings.ts [--write]
 *   --write  also regenerate supabase/seed.sql
 */

import { writeFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { expectedScore } from "../src/lib/elo";
import { LEGACY_PLAYERS, LEGACY_WINS, type LegacyPlayer } from "./data/legacy";

export interface InitialRatingOptions {
  pointsPerRatingStep: number;
  historyK: number;
  center: number;
}

export const DEFAULT_OPTIONS: InitialRatingOptions = { pointsPerRatingStep: 100, historyK: 12, center: 1500 };

export interface InitialRating {
  name: string;
  active: boolean;
  groupRating: number | null;
  prior: number;
  wins: number;
  rating: number;
}

const mean = (xs: number[]) => xs.reduce((s, x) => s + x, 0) / xs.length;

export function computeInitialRatings(
  players: LegacyPlayer[] = LEGACY_PLAYERS,
  wins: [string, string][] = LEGACY_WINS,
  options: InitialRatingOptions = DEFAULT_OPTIONS,
): InitialRating[] {
  const known = new Set(players.map((p) => p.name));
  for (const pair of wins) {
    for (const name of pair) if (!known.has(name)) throw new Error(`Unknown player in history: ${name}`);
  }

  const activeMean = mean(players.filter((p) => p.active && p.groupRating !== null).map((p) => p.groupRating!));
  const ratedMean = mean(players.filter((p) => p.groupRating !== null).map((p) => p.groupRating!));
  const toElo = (r: number) => options.center + options.pointsPerRatingStep * (r - activeMean);

  const rows = new Map<string, InitialRating>(
    players.map((p) => {
      const prior = toElo(p.groupRating ?? ratedMean);
      return [p.name, { name: p.name, active: p.active, groupRating: p.groupRating, prior, wins: 0, rating: prior }];
    }),
  );

  for (const [x, y] of wins) {
    const a = rows.get(x)!;
    const b = rows.get(y)!;
    const gain = options.historyK * (1 - expectedScore((a.rating + b.rating) / 2, options.center));
    a.rating += gain;
    b.rating += gain;
    a.wins++;
    b.wins++;
  }

  // Re-centre only players who appear in the history: not being on a list of
  // winners says nothing about someone who wasn't there.
  const appeared = [...rows.values()].filter((r) => r.wins > 0);
  const anchor = appeared.filter((r) => r.active).length > 0 ? appeared.filter((r) => r.active) : appeared;
  const shift = mean(anchor.map((r) => r.prior)) - mean(anchor.map((r) => r.rating));
  for (const r of rows.values()) r.rating = Math.round(r.wins > 0 ? r.rating + shift : r.prior);

  return [...rows.values()].sort((p, q) => Number(q.active) - Number(p.active) || q.rating - p.rating);
}

function seedSql(ratings: InitialRating[]): string {
  const esc = (s: string) => s.replace(/'/g, "''");
  const values = ratings
    .map((r) => `  ('${esc(r.name)}', ${r.rating}, ${r.rating}, ${r.active})`)
    .join(",\n");
  return `-- Generated by scripts/initial-ratings.ts — do not edit by hand.
-- Starting ratings derived from the group's 1–10 ratings and pre-app win history.

insert into public.players (name, initial_singles, initial_doubles, is_active)
values
${values}
on conflict (name) do update
  set initial_singles = excluded.initial_singles,
      initial_doubles = excluded.initial_doubles,
      is_active = excluded.is_active;
`;
}

function main() {
  const ratings = computeInitialRatings();
  const pad = (s: string | number, n: number) => String(s).padEnd(n);
  console.log(`${pad("Player", 10)} ${pad("Active", 7)} ${pad("1-10", 6)} ${pad("Prior", 6)} ${pad("Wins", 5)} Start`);
  for (const r of ratings) {
    console.log(
      `${pad(r.name, 10)} ${pad(r.active ? "yes" : "no", 7)} ${pad(r.groupRating ?? "-", 6)} ${pad(Math.round(r.prior), 6)} ${pad(r.wins, 5)} ${r.rating}`,
    );
  }
  if (process.argv.includes("--write")) {
    const out = fileURLToPath(new URL("../supabase/seed.sql", import.meta.url));
    writeFileSync(out, seedSql(ratings));
    console.log(`\nWrote ${out}`);
  }
}

if (process.argv[1] && fileURLToPath(import.meta.url) === process.argv[1]) main();
